// errorCodes.ts

export const ERROR_CODE_SERVER_FAILED = 'ERR_SERVER_FAILED'
export const ERROR_CODE_INVALID_PARAMS = 'ERR_INVALID_PARAMS';
export const ERROR_CODE_SUSPICIOUS_PAYLOAD = 'ERR_SUSPICIOUS_PAYLOAD';
export const ERROR_CODE_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND';
export const ERROR_CODE_AUTHENTICATION_FAILED = 'ERR_AUTHENTICATION_FAILED';
export const ERROR_CODE_SAME_PASSWORD_USED = 'ERR_SAME_PASSWORD_USED'
export const ERROR_CODE_INVALID_PASSWORD_SPECS = 'ERR_INVALID_PASSWORD_SPECS'

export default ERROR_CODE_SERVER_FAILED
// Add more error codes as needed
